### ISSUE TITLE
Silent option

### ISSUE THREAD

**Issue by te-gpm** [micahblu/gulp-connect-php#10]
I got gulp-connect-php to work in conjunction with browserSync, which works perfectly so far. 
I've been using grunt-php before which this plugin seems to be based on and I remember it having a silent flag to suppress the output to the console. I would very much like to have that feature as well since I use the console output for things like JSHint and don't really need a bunch of [200] access codes cluttering my console. I couldn't find a similar option for gulp-connect-php :(
Is there any way this can be implemented or achieved in my gulp setup?
Any help is much appreciated!

**Comment by awhatley** [comment]
I submitted a pull request for this here: https://github.com/micahblu/gulp-connect-php/pull/11

**Comment by micahblu** [comment]
I merged  https://github.com/micahblu/gulp-connect-php/pull/11 which gives a silent option
