### ISSUE TITLE
htaccess

### ISSUE THREAD

**Issue by benjamingeorge** [micahblu/gulp-connect-php#16]
Is there a way to use .htaccess file for pretty urls.  I put the .htaccess file in the directory i'm serving from but it doesn't work.  I tested the htaccess file out on a localhost and can confirm that it works properly.

**Comment by stevenpetryk** [comment]
`.htaccess` works because webservers support it. It's not a PHP thing. Connect does not support `htaccess`, and it definitely wouldn't be appropriate for this project to add support.
