### ISSUE TITLE
browsersync don't work with connect-php

### ISSUE THREAD

**Issue by gosteev** [micahblu/gulp-connect-php#20]
``` javascript
// ### Server tasks

// server w/ php
gulp.task('connect', function() {
  connect.server({
    hostname: 'localhost',
    bin: '/usr/bin/php',
    ini: '/etc/php5/cli/php.ini',
    base: './dist',
    keepalive: true,
  }, function (){
    browserSync.init({
      proxy: "localhost:8000",
      open: false
    });
  });
});

// server w/out php
gulp.task('connect-no-php', function() {
  browserSync.init({
    server: "./dist",
    open: false
  });
});
```

without connect-php `browserSync.reload()` and `browserSync.stream()` works fine. when i run `connect` task, it just don't want to refresh browser or inject styles, until i refresh page manually.
and...it happens only when i run linux. on windows there is no problem.

what it can be?

**Comment by micahblu** [comment]
what do you get from `which php`?

**Comment by gosteev** [comment]
`/usr/bin/php`

**Comment by buecklers** [comment]
I had that problem just right now on a windows installation and figured out that browser-sync does not connect with a raw php file as it doesn't find the body tag to append some javascript. It worked fine with a html file. 
So, I just added 

```
<script async="" src="/browser-sync/browser-sync-client.2.11.1.js"></script>
```

 on the bottom of my simple php file. And that worked for me.

**Comment by grmartin** [comment]
For now, @buecklers response should be followed: https://github.com/micahblu/gulp-connect-php/issues/20#issuecomment-173598269.

**Comment by ashishslodhi** [comment]
just add

`echo "<body></body>";`

at the start of php script
 
or 

simply add 

`<body></body>`

before opening php script

both ways are working for me.
