### ISSUE TITLE
Option to suppress logs

### ISSUE THREAD

**Issue by atdrago** [micahblu/gulp-connect-php#21]
Hello!

Would it be possible to add an option that suppressed logging? I don't really need to see every request on every page load in my terminal window. :)

Adam

**Comment by marcofugaro** [comment]
Yes! I use gulp-connect-php with browserSync and everytime it refreshes, it logs all the requests in the console, this bloats the console.

You have the `silent` option in browserSync, but not here.

EDIT: Just found out about [this merge](https://github.com/micahblu/gulp-connect-php/pull/11), I still don't know how to achieve the result, you should name the option kinda like `logLevel` [from browserSync](http://www.browsersync.io/docs/options/#option-logLevel) and add it to the documentation.

**Comment by atdrago** [comment]
You're right!

It looks like this option was added in 0.0.7, but NPM only has 0.0.5, which is why you probably can't see it. @micahblu Could you push 0.0.7 to NPM, please?

@marcofugaro To answer your question, setting stdio to [null, null, null] removes all logs. I don't know if this is "correct" or not, but it works. :)

Thanks,
Adam

**Comment by micahblu** [comment]
Just pushed latest to npm. Let me know if this doesn't work

**Comment by atdrago** [comment]
It works beautifully! Is `stdio: [null, null, null]` the correct thing to use to kill all logs?

**Comment by marcofugaro** [comment]
@atdrago I think the correct way is `stdio: 'ignore'` it works for me! thanks @micahblu

**Comment by atdrago** [comment]
Closing the issue. Thanks again @micahblu!
