### ISSUE TITLE
closeServer() does not work in Windows environment

### ISSUE THREAD

**Issue by ytkj** [micahblu/gulp-connect-php#23]
the method closeServer() does not work because 'lsof' command does not exist in Windows command.

``` javascript
var connect = require('gulp-connect-php');

// start server
connect.init();

// end server
connect.closeServer(); // error!
```

Whether this API is going to be supported in Windows, or not ?

**Comment by tdmalone** [comment]
I'm running into this as well. `netstat -bno` _might_ work as a replacement command for Windows, but it requires elevation and I couldn't get it to the show the PHP server anyway, so it might not help.

**Comment by tdmalone** [comment]
At the moment I'm getting around closing it using this:

```
.once( 'end' , function() {
  callback();
  process.exit();
});
```

Solution discovered [here](https://github.com/sindresorhus/gulp-mocha/issues/1#issuecomment-43454899).

You could also use [gulp-exit](https://www.npmjs.com/package/gulp-exit), but this doesn't appear to call the callback function.

**Comment by tdmalone** [comment]
The above solution will kill any other tasks you're running, so it's not a suitable solution unless you're not running anything else asynchronously. Here's another alternative:

```
.pipe( require( 'through2').obj( function( chunk, enc, callback ) {
    // kill php server so that we don't have a never-ending process
    require( 'child_process' ).exec( 'taskkill /F /IM php.exe', function( error, stdout, stderr ){
        callback( null, chunk );
    });
}));
```

This one, of course, has the downside of closing any other php process you might be running.

**Comment by grmartin** [comment]
This is resolved in the 1.0.0 WIP. Presently available here: https://github.com/micahblu/gulp-connect-php/pull/41

You are welcome (encouraged) to test that out and see how it goes.

Please direct any bugs against 1.0.0 WIP against the other repo (https://github.com/grmartin/gulp-connect-php). Once it is merged in to this one, bug tracking will move here, i simply do not wish to muddy the waters in this repo until after that branch is mainlined.

**Comment by grmartin** [comment]
1.0.0 is now in the primary master branch of the original repository. See: http://github.com/micahblu/gulp-connect-php.

**Comment by grmartin** [comment]
This ticket will close on or near 17 May 2017 unless updated.

**Comment by grmartin** [comment]
Closing marking as invalid due to inactivity since 1.0.
