### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by dylanh724** [micahblu/gulp-connect-php#25]
**EDITED**
# Created dir **C:\Test\**

**npm install --save-dev gulp-connect-php**

Browse to C:\Test\node_modules\gulp-connect-php\

I edited the index.js file to include a console.log("Starting.."); and that now shows ok (so it's doing something), 

but when I go to the examples folder and run "node gulpfile", I see starting... and that's it. I browse to the default localhost:8000 and nada. Just in case I try localhost:8000/index.php and nothing (even though it should default to index).

So I edit gulpfile.js and add a "Started" console log msg, and that NEVER shows up. **I am using 100% default example, minus the console message!**

...Am I doing something wrong?

(Still a node newb, bare with me, but I've followed all the instructions)

**Comment by marcospgp** [comment]
+1

**Comment by cdit** [comment]
You have to setup your environment variables.

Insert the path to your PHP directory into the "PATH" Variable and test it in console with "php -h". If you see php's syntax-help you should be fine.

**Comment by dylanh724** [comment]
Path is already set to php5, is 7 required or something?

**Comment by dylanh724** [comment]
(and that cmd works)

**Comment by cdit** [comment]
No. You only need at least PHP 5.4 for the integrated Webserver. Can you start a Webserver by cmd via "php -S"?

EDIT: which example do you use exactly? Did you setup the default task in gruntfile.js? Can you post your gruntfile.js and package.json.

**Comment by dylanh724** [comment]
yep php -S works great -- strange right? **Screen:**
http://imgur.com/E7Iwpjh 

I'm on Windows 10 - anything special about w10?

**Comment by grmartin** [comment]
@dylanh724 Is this still an issue for you?

**Comment by grmartin** [comment]
This ticket will close on or near 17 May 2017 unless updated.

**Comment by grmartin** [comment]
Closing marking as invalid due to inactivity since 1.0.
