### ISSUE TITLE
TypeError: Cannot set property 'build' of null

### ISSUE THREAD

**Issue by jabaa** [micahblu/gulp-connect-php#30]
I want to use php in node.js and created a new project:
- npm init -y
- npm install --save-dev gulp gulp-connect-php

I added a `gulpfile.js` with

```
var gulp = require('gulp');
var connect = require('gulp-connect-php');

gulp.task('php', function () {
    connect.server();
});
```

I started my project with `gulp php` and got

```
/home/jabaa/Documents/Projects/Web/php/node_modules/semver-truncate/index.js:11
    version.build = '';
                  ^

TypeError: Cannot set property 'build' of null
    at module.exports (/home/jabaa/Documents/Projects/Web/php/node_modules/semver-truncate/index.js:11:16)
    at /home/jabaa/Documents/Projects/Web/php/node_modules/bin-version-check/index.js:20:25
    at /home/jabaa/Documents/Projects/Web/php/node_modules/bin-version/index.js:15:3
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by zegerhoogeboom** [comment]
I am also currently experiencing this issue. 
Manually starting a php webserver works. (i.e.`$ php -S localhost:5000`)

This is my php version output.

```
$ which php
/usr/bin/php
$ php --version
PHP 7.0.8-0ubuntu0.16.04.1 (cli) ( NTS )
```

**Comment by jabaa** [comment]
It's a problem with bin-version-check. In node_modules/gulp-connect-php/index.js you can comment out line 107 `binVersionCheck(options.bin, '>=5.4', function (err) {`
line 108 `if (err) {`
line 109 `cb();`
line 110 `return;`
line 111 `}`
and line 133 `}.bind(this));`. 

That's not really a solution but it temporarily works.

**Comment by jeffstahlin** [comment]
I've been suffering the same issue. It's become a real pain to work with this issue, so thank you @jabaa for the temporary solution, works perfectly.

**Comment by kodekracker** [comment]
I also faced this issue and found out that this error is occurred because `7.0.8-0ubuntu0.16.04.1` is not valid semantic version. That's why `semantic-truncate` library raise this error. So, i created the [issue#2](https://github.com/sindresorhus/semver-truncate/issues/2) on [semantic-truncate](https://github.com/sindresorhus/semver-truncate) github repo. And, it's actually fixed now. So, you can reinstall `semver-truncate` library to get rid of this error.  Thanks to @sindresorhus .

**Comment by micahblu** [comment]
I'm closing this as solved per @kodekracker's insight on the issue being with semantic-truncate
