### ISSUE TITLE
BrowserSync with gulp-connect-php 

### ISSUE THREAD

**Issue by mitchrenton** [micahblu/gulp-connect-php#31]
The contents of my gulp task (serve) are below. All of the tasks are performing as expected, in the terminal I get the message `[BS] Reloading browsers...` as expected. But the browser doesn't reload. If I manually refresh, I see the changes that I'd made in either PHP, JS or CSS.

Any help here would be greatly appreciated.
### Versions of Browsersync, node and npm I'm running
- Browsersync [ 3.5.3 ]
- Node        [   5.5.0 ]
- Npm         [   3.5.3 ]
### Affected platforms
- [x] OS X
### Browsersync use-case
- [x] Gulp
### How I'm using gulp-connect-php with BrowserSync

```
'use strict';
const browserSync = require('browser-sync');
const connect = require('gulp-connect-php');
const gulp = require('gulp');

// Function to properly reload your browser
function reload(done) {
  browserSync.reload();
  done();
}

gulp.task('serve', function(done) {
  connect.server({
    base: './.tmp/app',
    hostname: 'localhost',
    port: 3000
  }, function (){
    browserSync.init({
      proxy: 'localhost:8000'
    });
    done();
  });

  gulp.watch('src/app/assets/javascript/**/*.js', gulp.series('scripts', reload));
  gulp.watch('src/app/assets/scss/**/*.scss', gulp.series('styles'));
  gulp.watch('src/**/*.php', gulp.series('phplint', 'copy:php', reload));

});


gulp.task('watch', function)
```

**Comment by micahblu** [comment]
Can you confirm the URL and the browser you're using?

**Comment by micahblu** [comment]
Closing this for now due to no response. Please feel free to reopen.
