### ISSUE TITLE
Not working with Grav CMS admin

### ISSUE THREAD

**Issue by julienchazal** [micahblu/gulp-connect-php#32]
Hello
I'm building a site with [Grav](http://getgrav.org) CMS, gulp-connect-php is working fine for rendering php pages.
But when i want to connect to the admin, i get a server error 500 : 

> The Admin Plugin cannot run on the PHP built-in webserver. It needs Apache, Nginx or another full-featured web server.

Is there a workaround please ?

thx

**Comment by micahblu** [comment]
Grav is stating that it requires a standard web server, you would need to create an issue or feature request with Grav to support non standard web servers such as this one.
