### ISSUE TITLE
closeServer does not work with non-8000 port 

### ISSUE THREAD

**Issue by jake-a-wood** [micahblu/gulp-connect-php#33]
For some reason, even though the code is updating the workingPort variable as you would expect, the previous value or workingPort is what is getting used during the closeServer method (8000). 

You can see the issue if you run server with port 9000 and then try and run closeServer. If you log out the workingPort value it will be 8000 instead of the expected 9000.

**Comment by grmartin** [comment]
Is this still an issue @jake-a-wood? Seems resolved to me.

**Comment by jake-a-wood** [comment]
```
const gulp = require('gulp')
const connect = require('gulp-connect-php')

gulp.task('connect', function() {
    connect.server({
        port: 9000,
        base: './public'
    }, function() {
        connect.closeServer();
    })
})

gulp.task('default', ['connect'])
```

When I run this, it complains that a `cb` function isn't provided.

If I do provide the callback function, it works as expected though.

**Comment by grmartin** [comment]
A callback function to 'closeServer' is required. At least that is how the code is presently written, i will ensure it is optional in `1.0.0`.

**Comment by grmartin** [comment]
https://github.com/micahblu/gulp-connect-php/pull/41 now has a fix. `closeServer` no longer requires a callback.

**Comment by jake-a-wood** [comment]
I find the current state easily worked around then. Thanks @grmartin!
