### ISSUE TITLE
Crash calling a batch under Windows

### ISSUE THREAD

**Issue by TigersWay** [micahblu/gulp-connect-php#40]
If a batch <php.bat> exists somewhere on the PATH, gulp-connect-php will crash trying to call it.
But set option <bin: 'php.bat'> and it will work!

Thanks to have a look!

**Comment by micahblu** [comment]
Happy to accept a working pr that addresses the issue

**Comment by grmartin** [comment]
@TigersWay 

Batch file support should be in the 1.0.0 WIP Branch, 

PR: https://github.com/micahblu/gulp-connect-php/pull/41
Information: https://github.com/grmartin/gulp-connect-php/tree/grmartin/rewrite-1.0.0

**Comment by grmartin** [comment]
1.0.0 is now in the primary master branch of the original repository. See: http://github.com/micahblu/gulp-connect-php.

**Comment by TigersWay** [comment]
Soo fast :-)
Loading it!
