### ISSUE TITLE
Crash when running version 1.0.0

### ISSUE THREAD

**Issue by focussing** [micahblu/gulp-connect-php#42]
Hi!

All the examples crash when run.
Installation of version 0.0.8 does not give errors when run using the same examples.

<project>/node_modules/gulp-connect-php/index.js:16
    [...arguments].forEach((x) => { this[x] = Symbol(x) });
     ^^^
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/raymond/Google Drive/sites/bolwerkenschede/gulpfile.js:5:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

environment: mac osx sierra

**Comment by grmartin** [comment]
@focussing The `[...arguments]` construct is part of the ES15 language, known as `Spread`. http://node.green/#ES2015-syntax-spread-------operator Are you by chance on Node 4.8.2 or earlier?

**Comment by focussing** [comment]
nope... node version is 4.6.2 (because of other tools for which that is max version of nodejs)

**Comment by focussing** [comment]
what is your required node version? maybe make that clear on the getting started page?

**Comment by grmartin** [comment]
That seems a fair choice... Ill ensure it ends up in the package manifest. Can you drop down to `0.0.8` for now?  Ill see if i can prep a second node package later today for ES5 support, won't be hard to automate with [Babel](http://babeljs.io) i'd think.

**Comment by focussing** [comment]
Thanks!!
0.0.8 will do for me (I think).. I only needed ur plugin because I have a SQLITE database which is accessed by a PHP script. Or do you have a suggestion to do that another way?

**Comment by grmartin** [comment]
I suppose it depends on your requirements, id be happy to discuss them with you... NPM has a number of [SQLite](https://npms.io/search?q=sqlite+not%3Adeprecated) direct access packages, i suppose the question is, does the PHP script manipulate the results in anyway? Are these packages available on an older node version such as yours? And what OS are you working on? All of them have fair ways of running this stuff via the CLI which might be 'faster' (spinning up a server even a lightweight one is process) but less 'safe' (Prone to CLI Injection).

**Comment by focussing** [comment]
yep, the php script is an SQLITE CRUD engine for the CMS (own creation) which enables the user to edit content (not structure) of the website. The index.html itself only reads the content via AngularJS.

**Comment by grmartin** [comment]
Well, that leaves you with two choices id think. 1. Create a CLI wrapper... 2. Launch an AdHoc server... 2 is the path of least resistance id think. Im afraid i dont really have any additional suggestions on this one.

Im going to leave this ticket open until i have a second package, or have atleast added the Node engine version to the package.json file.

**Comment by brisa-pedronetto** [comment]
Hi, I'm having the exact same problem. My node version is 4.4.3 and npm is 3.8.8, it should be working, right? Is there a way to tell node to transpile my dependencies before requiring them?

<img width="720" alt="screen shot 2017-05-09 at 19 14 04" src="https://cloud.githubusercontent.com/assets/13985387/25868331/d946ac16-34eb-11e7-84fa-9ae800901d3f.png">


Thank you!

**Comment by grmartin** [comment]
There is a backroom conversation on this, stay tuned.

**Comment by MiguelDebruyne** [comment]
Same problem on 
OSX El Capitan 10.11.6
Node 4.6.1
Gulp 3.9.0

**Comment by grmartin** [comment]
@MiguelDebruyne Yeah, any node before 5.0 will have this issue. We have a fix, i just need to get it finished ;) for now fallback to 0.8.
