### ISSUE TITLE
Cache with gulp-connect-php

### ISSUE THREAD

**Issue by davidrhoderick** [micahblu/gulp-connect-php#46]
I cannot figure out if it is my code or if gulp-connect-php just doesn't have any caching capabilities.  From what I can tell in running `phpinfo();`, memcache, memcached, and apc are all running or emulated.  However, when I try any of the tests of memcache or memcached, I can't connect to anything.  Does gulp-connect-php just not support caching even though it says it does in phpinfo?

**Comment by grmartin** [comment]
`gulp-connect-php` Doesn't determine anything about the runtime really... if you need to you can use the flag setter to do so... the truth is this is merely a script to wrap the execution of the php interpretative in its debug server mode....

Memcache typically has a daemon component, is that running?

**Comment by davidrhoderick** [comment]
So if I run the following code:

    $m = new Memcached();
    var_dump($m->addServer('localhost', 11211));
    var_dump($m->getResultCode());
    var_dump($m->set('hereisakey', 123));
    var_dump($m->get('hereisakey'));

I get the following response:

    boolean true
    int 0
    boolean false
    boolean false

So that means that it is connected but I am unable to set a variable.  I suppose this is no longer a gulp-connect-php issue but if you can help, that would be fantastic.

**Comment by grmartin** [comment]
@davidrhoderick 

Mind running the following?

```php
$m = new Memcached();
var_dump($m->addServer('localhost', 11211));
var_dump($m->getResultCode());
var_dump($m->set('hereisakey', 123));
var_dump($m->getResultCode());
var_dump($m->get('hereisakey'));
var_dump($m->getResultCode());
```

and letting me know the result?

There is also the [`memcache_debug(bool)`](http://php.net/manual/en/function.memcache-debug.php) call which might help. 

And while i havent used memcache in a while... manually connecting can be useful to test connection related issues (rather than pooling... pooling is great for production, but sometimes simplifying the connection handling while trying to get something running is helpful). ... and dont rely on [`Memcache::getServerStatus`](http://php.net/manual/en/memcache.getserverstatus.php)... it [lies](http://php.net/manual/en/memcache.getserverstatus.php#99005)... try [`Memcache::getExtendedStats`](http://php.net/manual/en/memcache.getextendedstats.php) instead.

**Comment by grmartin** [comment]
(im marking this as `invalid` since its not due to the plugin but ill help if i can anyway.)

**Comment by davidrhoderick** [comment]
@grmartin not a problem; it is invalid.  And thank you for your help.  I get the following:

    boolean true
    int 0
    boolean false
    int 47
    boolean false
    int 47

Which means memcached is temporarily disabled, right?  I am on Mac OS X, which file and how do I enable it?  I'll start looking online for that now....

**Comment by grmartin** [comment]
@davidrhoderick (yes [`MEMCACHED_SERVER_TEMPORARILY_DISABLED` is `47`](http://bazaar.launchpad.net/~tangent-trunk/libmemcached/1.0/view/head:/libmemcached-1.0/types/return.h#L87)) How did you install memcached? [Homebrew](https://brew.sh)?

If so your command is `brew info memcached`... on my machine i get the following:

```
Last login: Fri Jul 21 12:05:05 on console
Glenns-MacBook-Pro:~ grmartin$ brew info memcached
memcached: stable 1.4.37 (bottled)
High performance, distributed memory object caching system
https://memcached.org/
Conflicts with:
  mysql-cluster (because both install `bin/memcached`)
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/memcached.rb
==> Dependencies
Required: libevent ✘
==> Options
--with-sasl
	Enable SASL support -- disables ASCII protocol!
--with-sasl-pwdb
	Enable SASL with memcached's own plain text password db support -- disables ASCII protocol!
==> Caveats
To have launchd start memcached now and restart at login:
  brew services start memcached
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/memcached/bin/memcached
Glenns-MacBook-Pro:~ grmartin$ 
```

which informs me to invoke: `brew services start memcached`. (Though i have a conflict with mysql on my machine)

**Comment by grmartin** [comment]
You can use telnet (telnet to the port 11211) and type `status<enter>` to see if its up... there are also web-guis and im sure somewhere a Java or MacOS Gui for it.

**Comment by davidrhoderick** [comment]
@grmartin You're the best!  I just reinstalled it and it worked!  I'm closing this now.  Thanks a lot!
