### ISSUE TITLE
Can't run server from custom bin directory

### ISSUE THREAD

**Issue by dessery85** [micahblu/gulp-connect-php#49]
Hi

I have a custom PHP installation setup in /usr/local/php5/bin/php. I am trying to get a PHP server running from this bin directory but I am having some problems, my gulpfile includes the following:

`connect.server(
        {
            base: '../../../',
            port: 8010,
            keepalive: true,
            debug: true,
            stdio: 'ignore',
            bin: '/usr/local/php5/bin/php'
        });`

However, when i run the server I get the following message:

`Invoking Spawn with:
/usr/local/php5/bin/php
[ '-S', '127.0.0.1:8010', '-t', '../../../' ]
{ cwd: '.', stdio: 'ignore' }
PHP server not started. Retrying...`

However if I run the following command myself in terminal from the same folder it runs absolutely fine:

`/usr/local/php5/bin/php -S 127.0.0.1:8010 -t ../../../`

I have tried debugging through the JS and I can confirm that the checkPath call is saying that the bin file exists. If i log out the error that is returning when it is logging 'PHP server not started', i get the following:

`{ Error: connect ECONNREFUSED 127.0.0.1:8010
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8010 }`

Any help to get this working would be greatly appreciated!!

Many thanks
David

**Comment by grmartin** [comment]
There is a chance the server is breaking off `ECONNREFUSED` via the `connect` call is at the socket level and typically means one of two things... 1. You don't have permission to use this port (not usually the case of the port number is higher than 1024). 2. Something else is open on that port. Tools such as `lsof` or `netstat` can help you there... however if bet it's a hanging instance of PHP, which can be terminated (if the system is used only by you) by executing `killall php`.

**Comment by dessery85** [comment]
Hi @grmartin 

Many thanks for getting back to me so quickly. I can confirm that the port is not in use as I can still run the command directly from terminal using the same port number which should also mean that permissions are fine too.

Many thanks
David

**Comment by grmartin** [comment]
So on a secondary review the error is coming from Node. Is there anything in the form of extensions or startup additions (in `php.ini`) that could slow it down? I don't think there is a delay for startup of the checking system.

**Comment by dessery85** [comment]
Hi @grmartin 

Many thanks for taking another look, it appears you may be right, I just tried to start it up and went to make a drink and came back and it was working, it must of taken quite a while because i did leave it a good few minutes before but it has started. Strange though because it starts instantly if I enter the command directly into terminal. 

I don't have anything special in php.ini, its pretty much a stock configuration so not sure if it could be anything there causing the problem.

Many thanks for your help on this

All the best
David
