### ISSUE TITLE
Allow more than one string for the base path

### ISSUE THREAD

**Issue by smohadjer** [micahblu/gulp-connect-php#53]
One feature of gulp-connect is that it accepts an array of strings for the root path. This is very useful when build process creates files outside root folder of the project (such as in a tmp folder) that should be served. An example would be when stylesheets are in .sass format in root of project, but are converted to .css by build and served from a tmp folder. Example from gulp-connect:

```
gulp.task('connectDev', function () {
  connect.server({
    name: 'Dev App',
    root: ['app', 'tmp'],
    port: 8000,
    livereload: true
  });
});
```

**Comment by grmartin** [comment]
[PHP's Development Server](https://secure.php.net/manual/en/features.commandline.webserver.php) is the hangup here. We pass the base path off to PHP and let it manage it... In these cases i have used a false base-path and a routing script... Its certainly not optimal from an 'ease of configuration' perspective, but i feel if we obscure this fact by trying to implement a feature that writes one on it own we will complicate the lives of others expecting it to work just like `gulp-connect`'s and those who want to use multiple roots with a routing script of their own.

An example routing script can be found on within the above link. If you need more information, ill be happy to assist.
