### ISSUE TITLE
when opening php file chrome downloads it

### ISSUE THREAD

**Issue by tanishbaansal** [micahblu/gulp-connect-php#57]
opening the php file but when write the url like localhost:8000/php/a.php the file gets downloaded ... using browsersync also

**Comment by micahblu** [comment]
Hi @tanishbaansal  I'm not able to reproduce. From this cloned repo, can you please try adding a.php inside "examples/simple/" with `<?php echo "You are viewing a.php :)"; ?>` in it. 

Then `cd example/simple && npm i gulp` 
Once npm loads the local gulp, run `gulp` then go to your browser and visit localhost:8000/a.php.
