### ISSUE TITLE
Add functionality to pass command line args to PHP

### ISSUE THREAD

**Issue by nsrosenqvist** [micahblu/gulp-connect-php#58]
It'd be great if the package supported setting custom command line arguments to PHP. Currently I need to add some extra stuff to enable a profiler and I do it by setting it in the router property, but it'd be great if it could be officially supported. Thanks!

**Comment by grmartin** [comment]
@nsrosenqvist please see https://github.com/micahblu/gulp-connect-php#configcallback

You can see the implementation in https://github.com/micahblu/gulp-connect-php#advanced-option-manipulation on the line that is `      } else if (type === connect.OPTIONS_PHP_CLI_ARR) { // As the constant suggests, collection is an Array.`

**Comment by grmartin** [comment]
Add to your config:
```php
configCallback: function _configCallback(type, collection) {
    if (type === connect.OPTIONS_PHP_CLI_ARR) { // As the constant suggests, collection is an Array.
        let newArgs = [
          '-e',                     // Generate extended information for debugger/profiler.
          '-d', 'memory_limit=2G'   // Define INI entry, Up memory limit to 2G.
        ];

        // Ensure our argument switches appear before the rest.
        return newArgs.concat(collection);
      }
    }
```

**Comment by nsrosenqvist** [comment]
Thanks!
