### ISSUE TITLE
Odd issue with server occasionally stopping completely

### ISSUE THREAD

**Issue by scottlet** [micahblu/gulp-connect-php#59]
So I'm using this to run a wordpress instance. Loading pages is fine but after a while (maybe 20-30 minutes) of refreshing whilst I work on a theme the server will suddenly die, first it'll return nothing, then it'll give connection refused.

Locally I'm running on port 8888 and I can reliably reproduce by hitting this URL `http://172.16.1.2:8888/wp-content/themes/wp-theme/js/scripts-0.0.1.min.js`

When this happens, there's no log output, running the task in gulp with DEBUG=* gives no log output, there's nothing in the wordpress log, setting the debug option also gives no output.

Do you have any idea what could cause this or how I could go about trying to debug? If not I can probably create an environment that'll hopefully allow you to reproduce this but it may take a little while.

OSX Mojave (but also happens in other OSXes)

/usr/local/bin/php
php -v
PHP 7.2.10 (cli) (built: Sep 14 2018 07:07:08) ( NTS )
gulp -v
[07:10:36] CLI version 3.9.1
[07:10:36] Local version 3.9.1
node -v
v10.11.0

**Comment by scottlet** [comment]
Fixed (I think).
In case anyone has a similar issue, I had a trailing slash in my `base` option. Removing this corrects the issue.

**Comment by grmartin** [comment]
Very cool. This sounds like a small issue with the PHP Dev Server App.

**Comment by scottlet** [comment]
Further info - it seems to be an error with running wordpress in the PHP dev server app. IF I proxy as many of the static resources as possible so they're served by connect directly then it seems to be less of a problem - I suspect for some reason 404s are killing the PHP dev server as there's a few of them, especially in the admin interface.

So I'm running this as a standalone and then proxying `^/(wp-admin|wp-includes|wp-content)/((?!.*php).*)` and it's stable.

Shoddy code example here ;)
https://github.com/scottbert/wordpress-theme-builder/blob/master/gulp-tasks/server.js
