### ISSUE TITLE
Push version 0.0.5 to npm

### ISSUE THREAD

**Issue by iskrisis** [micahblu/gulp-connect-php#7]
I don't know if it just takes time but maybe you forgot.

Latest version on npm is still 0.0.3, version which doesnt have the callback when server starts thus breaking the browser-sync examples in docs.

Thanks!

**Comment by mortenc** [comment]
I have the same issue - looking to integrate this great plugin in my gulp workflow, but the version 0.0.3, which is currently on NPM does not work with BrowserSync :)

**Comment by micahblu** [comment]
0.0.5 is up on npm, just checked. Make sure you update your package.json to the correct version

**Comment by mortenc** [comment]
Yep 0.0.5 is up on NPM now - thanks a lot!
