### ISSUE TITLE
Config option to limit logs to errors only

### ISSUE THREAD

**Issue by bradymwilliams** [micahblu/gulp-connect-php#9]
So far it works flawlessly, though the output to the console is very verbose. I, and im sure a few others would like an option to limit this output to errors only.

Great work, thanks!

**Comment by idanb11** [comment]
:+1:  totally agree

**Comment by awhatley** [comment]
My [pull request](https://github.com/micahblu/gulp-connect-php/pull/11) should allow you to do this, by setting the `options.stdio` value to `['ignore', 'ignore', process.stderr]`

**Comment by micahblu** [comment]
I've merged [this](https://github.com/micahblu/gulp-connect-php/pull/11). Should be good to go
